openai_api_key = "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"
Add OpenAI API key for Streamlit
