openai_api_key = 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
Add OpenAI API key for Streamlit
